version: "3"
services:
  nginx:
    build: ./nginx/
    container_name: b_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./code/:/data/code:rw
      - ./nginx/conf/conf.d/:/etc/nginx/conf.d/:ro
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf/vhost/:/etc/nginx/vhost/:ro
      - ./nginx/logs/:/var/log/nginx/:rw
    links:
      - php

  mysql:
    build: ./mysql/
    container_name: b_mysql
    ports:
      - "3306:3306"
    volumes:
      - ./code/:/data/code/:rw
      - ./mysql/conf:/etc/mysql/
      - ./mysql/logs:/var/log/mysql/
      - ./mysql/data:/var/lib/mysql/

  php:
    build: ./php/
    container_name: b_php
    ports:
      - "9000:9000"
    volumes:
      - ./code/:/data/code/:rw
      - ./php/logs/:/data/logs/:rw
      - ./php/conf/:/usr/local/etc/php/
    links:
      - mysql
      - redis
      - memcached

  redis:
    build: ./redis/
    container_name: b_redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis/conf/redis.conf:/etc/nginx/conf.d/:ro
      - ./redis/data/:/data

  memcached:
    build: ./memcached/
    container_name: b_memcached
    ports:
      - "11211:11211"
