version: "3"

networks:
  bnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.1/24

services:
  nginx:
    build: ./nginx/
    container_name: b_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./code/:/data/code:rw
      - ./nginx/conf/conf.d/:/etc/nginx/conf.d/:rw
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf/vhost/:/etc/nginx/vhost/:rw
      - ./nginx/logs/:/var/logs/nginx/:rw
    links:
      - php
    networks:
      bnet:
        ipv4_address: 192.168.0.5

  mysql:
    build: ./mysql/
    container_name: b_mysql
    ports:
      - "3306:3306"
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_VERSION=5.7
    volumes:
      - ./code/:/data/code/:rw
      - ./mysql/conf/mysql.conf:/etc/mysql/conf.d/my.cnf:ro
      - ./mysql/logs:/var/logs/mysql/:rw
      - ./mysql/data:/var/lib/mysql/:rw
    networks:
      bnet:
        ipv4_address: 192.168.0.6

  php:
    build: ./php/
    container_name: b_php
    ports:
      - "9000:9000"
    volumes:
      - ./code/:/data/code/:rw
      - ./php/logs/:/var/logs/:rw
      - ./php/conf/php.ini:/usr/local/etc/php/conf.d/php.ini:ro
      - ./php/conf/php-fpm.conf:/usr/local/etc/php-fpm.d/php-fpm.conf:ro
    links:
      - mysql
      - redis
      - memcached
    networks:
      bnet:
        ipv4_address: 192.168.0.7

  redis:
    build: ./redis/
    container_name: b_redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis/conf/:/etc/redis/:ro
      - ./redis/data/:/var/run/redis/:rw
      - ./redis/logs/:/var/logs/:rw
    networks:
      bnet:
        ipv4_address: 192.168.0.8

  memcached:
    build: ./memcached/
    container_name: b_memcached
    ports:
      - "11211:11211"
    networks:
      bnet:
        ipv4_address: 192.168.0.10