name: Build PHP Docker

on:
  schedule:
    - cron: "15 10 * * *"
  push:
    branches: [master]
    # Publish semver tags as releases.
    tags: ["v*.*.*"]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [7.2, 7.3, 7.4, 8.0]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - run: chmod +x blank.sh
      - name: Log into docker
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: sed 's/\(PHP_VERSION=\).*/\1${{ matrix.name }}/g' .env.example > .env
      - name: Build
        run: ./blank.sh d build php
      - name: Push image
        if: ${{ github.event_name != 'pull_request' }}
        run: docker-compose push php
